# Generated by Django 4.1.1 on 2022-09-24 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.position'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.shift'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='training',
            field=models.ManyToManyField(related_name='users', to='api.training'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.zone'),
        ),
        migrations.CreateModel(
            name='TrainingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings_user', to='api.training')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_training', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
