version: '3.9'

services:

  db:
    image: postgres:15.1-alpine
    container_name: ${PSQL_HOST}
    restart: always
    environment:
      - POSTGRES_USER=${PSQL_USER}
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
      - POSTGRES_DB=${PSQL_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  back-end:
    build: ./back
    volumes:
      - ./back/:/usr/src/back/
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
