from telegram.ext import ConversationHandler


CHOOSING = 'CHOOSING'
TYPING_REPLY = 'TYPING_REPLY'
TYPING_CHOICE = 'TYPING_CHOICE'
REGISTRATION = 'REGISTRATION'
ADD_MYSELF = 'ADD_MYSELF'
CHOOSE_ACTION = 'CHOOSE_ACTION'
CONFIRM = 'CONFIRM'
DISAGREE = 'DISAGREE'
NAME = 'NAME'
LAST_NAME = 'LAST_NAME'
PATRONYMIC = 'PATRONYMIC'
EMPLOYEE_ID = 'EMPLOYEE_ID'
TYPING = 'TYPING'
PHOTO = 'PHOTO'
SHIFT = 'SHIFT'
POSITION = 'POSITION'
SHOP = 'SHOP'
ZONE = 'ZONE'
CHOOSE_EDIT_INFO = 'CHOOSE_EDIT_INFO'
SAVE_TYPING_ANSWER = 'SAVE_TYPING_ANSWER'
SAVE_CHOOSING_ANSWER = 'SAVE_CHOOSING_ANSWER'

END = ConversationHandler.END
