# Generated by Django 4.1.1 on 2022-09-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_downtimetype_downtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downtime",
            name="time_start",
            field=models.DateTimeField(),
        ),
    ]
